version: "3.7"

services:
    frontend:
      container_name: dart_frontend
      build:
        context: ./frontend
        dockerfile: dev.Dockerfile
      volumes:
        - ./frontend/src:/usr/app/src
        - ./frontend/public:/usr/app/public
      depends_on:
        - api
      restart: on-failure
      ports:
        - 3000:3000
      # networks:
      #   - back
      #   - front

    api:
      container_name: dart_api
      build: ./api
      restart: on-failure
      depends_on:
        - db
      ports:
        - 8080:80
      # networks:
      #   - front

    db:
      container_name: dart_db
      build: ./database
      restart: on-failure
      volumes:
        - pg-data:/var/lib/postgresql/data
      environment:
        - DART_DB_USER=dart
        - DART_DB_PASSWORD=dart
        - DART_DB_DATABASE=dart
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432
      # networks:
      #   - back

volumes:
  pg-data:

# networks:
#   back:
#       external: false
#   front:
#       external: true
#       name: public

