version: '3.7'

services:
    frontend:
      build:
        context: './frontend'
        dockerfile: 'dev.Dockerfile'
      volumes:
          - ./frontend/src:/usr/app/src
          - ./frontend/public:/usr/app/public
      restart: on-failure

    db:
      build: './database'
      restart: on-failure
      volumes:
        - ./database/volumes/dev:/var/lib/postgresql/data
      environment:
        - "DART_DB_USER=dart"
        - "DART_DB_PASSWORD=dart"
        - "DART_DB_DATABASE=dart"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=postgres"
      ports:
        - 5432:5432